services:
  - type: web
    name: ieee-game-server
    runtime: node
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build && cd ../server && npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
